<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Owner Statement — {{ $monthLabel }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; color: #1a1a1a; background: #fff; }
  .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
  .brand { font-size: 24px; font-weight: 700; letter-spacing: 2px; }
  .brand span { color: #888; }
  .doc-title { font-size: 16px; font-weight: 700; text-align: center; margin-bottom: 4px; text-transform: uppercase; }
  .doc-subtitle { text-align: center; color: #555; margin-bottom: 20px; }
  .summary-grid { display: flex; gap: 0; margin-bottom: 24px; border: 1px solid #ccc; }
  .summary-cell { flex: 1; padding: 14px 16px; border-right: 1px solid #ccc; }
  .summary-cell:last-child { border-right: none; }
  .summary-label { font-size: 9px; color: #555; text-transform: uppercase; letter-spacing: 0.5px; }
  .summary-value { font-size: 16px; font-weight: 700; margin-top: 4px; }
  table.main { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  table.main th { background: #1a1a1a; color: #fff; padding: 7px 8px; text-align: left; font-weight: 600; }
  table.main td { padding: 7px 8px; border-bottom: 1px solid #f0f0f0; vertical-align: top; }
  table.main tr:nth-child(even) td { background: #f8f8f8; }
  .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin: 16px 0 10px; }
  .total-row td { background: #1a1a1a !important; color: #fff; font-weight: 700; }
  .footer { margin-top: 32px; border-top: 1px solid #ccc; padding-top: 8px; text-align: center; font-size: 9px; color: #888; }
</style>
</head>
<body>

<div class="header">
  <div class="brand">Estate<span>Yard</span></div>
  <div style="text-align:right; font-size:10px; color:#555;">
    <div style="font-weight:700;">Monthly Owner Statement</div>
    <div>{{ $monthLabel }}</div>
    <div>Generated: {{ now()->format('d F Y') }}</div>
  </div>
</div>

<div class="doc-title">Landlord Income Statement</div>
<div class="doc-subtitle">{{ $user->name }} &nbsp;·&nbsp; {{ $user->email }} &nbsp;·&nbsp; Period: {{ $monthLabel }}</div>

<div class="summary-grid">
  <div class="summary-cell">
    <div class="summary-label">Total Properties</div>
    <div class="summary-value">{{ $properties->count() }}</div>
  </div>
  <div class="summary-cell">
    <div class="summary-label">Rent Collected</div>
    <div class="summary-value">KES {{ number_format($totalCollected, 0) }}</div>
  </div>
  <div class="summary-cell">
    <div class="summary-label">Total Payments</div>
    <div class="summary-value">{{ $properties->flatMap->rentPayments->count() }}</div>
  </div>
  <div class="summary-cell">
    <div class="summary-label">Avg Per Property</div>
    <div class="summary-value">KES {{ $properties->count() > 0 ? number_format($totalCollected / $properties->count(), 0) : '0' }}</div>
  </div>
</div>

@foreach($properties as $property)
<div class="section-title">{{ $property->title }} &nbsp;·&nbsp; {{ $property->county }}, {{ $property->location }}</div>

@if($property->rentPayments->count() > 0)
<table class="main">
  <thead>
    <tr>
      <th>Receipt #</th>
      <th>Tenant</th>
      <th>Payment Date</th>
      <th>Method</th>
      <th>Amount (KES)</th>
    </tr>
  </thead>
  <tbody>
    @foreach($property->rentPayments as $payment)
    <tr>
      <td>{{ $payment->transaction_ref ?? 'RCP-' . str_pad($payment->id, 6, '0', STR_PAD_LEFT) }}</td>
      <td>{{ optional($payment->tenant)->name ?? 'N/A' }}</td>
      <td>{{ $payment->paid_at ? $payment->paid_at->format('d M Y') : 'N/A' }}</td>
      <td>{{ strtoupper($payment->method ?? 'N/A') }}</td>
      <td style="text-align:right; font-weight:600;">{{ number_format($payment->amount, 0) }}</td>
    </tr>
    @endforeach
    <tr class="total-row">
      <td colspan="4" style="text-align:right;">Property Subtotal</td>
      <td style="text-align:right;">{{ number_format($property->rentPayments->sum('amount'), 0) }}</td>
    </tr>
  </tbody>
</table>
@else
<p style="color:#999; font-size:10px; padding:8px 0; margin-bottom:12px;">No payments recorded for this property in {{ $monthLabel }}.</p>
@endif
@endforeach

<table class="main" style="margin-top:16px;">
  <tbody>
    <tr class="total-row">
      <td style="font-size:12px;">TOTAL INCOME — {{ $monthLabel }}</td>
      <td style="text-align:right; font-size:14px;">KES {{ number_format($totalCollected, 2) }}</td>
    </tr>
  </tbody>
</table>

<div class="footer">
  This statement was generated by EstateYard ERP Platform on {{ now()->format('d F Y \a\t H:i') }}. For queries, contact support@estateyard.com
</div>

</body>
</html>
