<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Rent Receipt</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #1a1a1a; background: #fff; }
  .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
  .brand { font-size: 24px; font-weight: 700; letter-spacing: 2px; }
  .brand span { color: #888; }
  .receipt-badge { background: #1a1a1a; color: #fff; padding: 4px 12px; font-size: 10px; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; display: inline-block; margin-bottom: 16px; }
  .amount-box { background: #f8f8f8; border: 1px solid #ccc; border-radius: 4px; padding: 20px; text-align: center; margin: 20px 0; }
  .amount-label { font-size: 10px; color: #555; text-transform: uppercase; letter-spacing: 1px; }
  .amount-value { font-size: 32px; font-weight: 700; margin: 8px 0; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 7px 8px; vertical-align: top; border-bottom: 1px solid #f0f0f0; }
  .label { color: #555; width: 40%; }
  .value { color: #1a1a1a; font-weight: 500; }
  .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 8px; text-align: center; font-size: 9px; color: #888; }
  .status-paid { background: #e6f7e6; color: #1a7f1a; padding: 2px 8px; border-radius: 2px; font-weight: 600; }
</style>
</head>
<body>

<div class="header">
  <div class="brand">Estate<span>Yard</span></div>
  <div style="text-align:right; font-size:10px; color:#555;">
    @php
      $ref = $payment->transaction_ref ?? 'RCP-' . str_pad($payment->id, 8, '0', STR_PAD_LEFT);
    @endphp
    <div style="font-weight:700; font-size:14px;">{{ $ref }}</div>
    <div>{{ $payment->paid_at ? $payment->paid_at->format('d F Y') : now()->format('d F Y') }}</div>
  </div>
</div>

<div class="receipt-badge">Official Payment Receipt</div>

<div class="amount-box">
  <div class="amount-label">Amount Paid</div>
  <div class="amount-value">KES {{ number_format($payment->amount, 2) }}</div>
  <span class="status-paid">PAID</span>
</div>

<table>
  <tr>
    <td class="label">Receipt Number</td>
    <td class="value">{{ $ref }}</td>
  </tr>
  <tr>
    <td class="label">Tenant</td>
    <td class="value">{{ optional($payment->tenant)->name ?? 'N/A' }}</td>
  </tr>
  <tr>
    <td class="label">Landlord</td>
    <td class="value">{{ optional($payment->landlord)->name ?? 'N/A' }}</td>
  </tr>
  <tr>
    <td class="label">Property</td>
    <td class="value">{{ optional(optional($payment->lease)->property)->title ?? 'N/A' }}</td>
  </tr>
  <tr>
    <td class="label">Location</td>
    <td class="value">{{ optional(optional($payment->lease)->property)->location ?? '' }}, {{ optional(optional($payment->lease)->property)->county ?? '' }}</td>
  </tr>
  <tr>
    <td class="label">Payment Method</td>
    <td class="value">{{ strtoupper($payment->method ?? 'N/A') }}</td>
  </tr>
  <tr>
    <td class="label">Payment Date</td>
    <td class="value">{{ $payment->paid_at ? $payment->paid_at->format('d F Y \a\t H:i') : 'N/A' }}</td>
  </tr>
  <tr>
    <td class="label">Period</td>
    <td class="value">{{ $payment->paid_at ? $payment->paid_at->format('F Y') : ($payment->due_date ? \Carbon\Carbon::parse($payment->due_date)->format('F Y') : 'N/A') }}</td>
  </tr>
</table>

<div style="margin-top:24px; padding:12px; border:1px dashed #ccc; text-align:center; font-size:10px; color:#555;">
  <!-- QR Code Placeholder -->
  <div style="display:inline-block; width:80px; height:80px; border:1px solid #ccc; background:#f8f8f8; line-height:80px; font-size:9px; color:#aaa; margin-bottom:8px;">QR CODE</div><br>
  Scan to verify this receipt at estateyard.com/verify/{{ $ref }}
</div>

<div style="margin-top:20px; font-size:10px; color:#555; text-align:center;">
  This receipt confirms payment has been received in full. Please retain for your records.
</div>

<div class="footer">
  Generated by EstateYard ERP Platform · {{ now()->format('d F Y \a\t H:i') }} · estateyard.com
</div>

</body>
</html>
