[program:hk-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/hustlekonnect/apps/api/artisan queue:work redis --queue=payments,notifications,bookings,default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/hk-worker.log
stopwaitsecs=3600
